### PR TITLE
Rewrote map drastically and added sample Europe trip

### PR DESCRIPTION
**Pull request by individual8**
No need for visualize.py anymore, just put in the array of POI in the optimizedRoute JS array in this HTML file and way you go...

Also added a fitBounds after polylines are rendered...

The set of waypoints is the same I wrote about in my post on Google+: http://goo.gl/luur2R

### CODE REVIEW

**Comment by rhiever** [comment]
Fantastic! Thank you for the PR. :+1:

**Comment by rhiever** [comment]
Actually: Can you explain how this works? Is there no limit to the number of waypoints if the `optimize waypoints` flag is off?

**Comment by individual8** [comment]
I took the functionality from visualize.py. It takes waypoints in steps of 10 items and pulls directions in the same form like you did, start, end and max. 8 stopovers.

Instead of declaring specific variables for the DirectionsRenderers I push them all in an array. So, as I said, the functionality more or less is the same. You just put the result of the genetic algorithm in the HTML file and JS splits it up in arrays of 10 and requests the DirectionsService to render the polylines.

**Comment by rhiever** [comment]
Ahh, I see what you're doing now! You pre-chunk the stops in the code. Very nice. I will have to rework my code to do this when I get more time.

I was speaking of the `optimizeWaypoints` parameter, which you set to `false`. But now I see that that has no effect here.

**Comment by individual8** [comment]
Exactly.

**Comment by individual8** [comment]
That flag you're talking about is set to false in your code too. If set to true the Maps API would shuffle around stopovers itself. I don't think that's necessary, since we don't want it to fiddle with the order.

**Pull request merged**
